version: "3"
services:
  nuxt-app:
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - ruksms
  server:
    build: ./server
    ports:
      - "4000:4000"
    networks:
      - ruksms
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - ruksms
    volumes:
      - mongo-data:/data/db
networks:
  ruksms:
    driver: bridge
volumes:
  mongo-data:
    driver: local
